### ISSUE TITLE
IP spoofing.

### ISSUE THREAD

**Issue by 10maurycy10** [ZeroTixDev/Darrows#19]
IP spoofing is possible if the server is *not* behind an http proxy, by setting the ``x-forwarded-for`` header.

**Comment by 10maurycy10** [comment]
This could be fixed with a config flag determining whether the server should trust ``x-forwarded-for``

**Comment by ZeroTixDev** [comment]
> IP spoofing is possible if the server is _not_ behind an http proxy, by setting the `x-forwarded-for` header.

I can enforce https on herokuapp domain

**Comment by 10maurycy10** [comment]
How will this help?

**Comment by 10maurycy10** [comment]
UPDATE: this is possible even with heroku.

**Comment by ZeroTixDev** [comment]
Fixed now
